version: "3"

services:
  
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smallfiles
    networks:
      intra:
        ipv4_address: 172.16.232.14
  
  app:
    image: 14315555/demo-restapi:latest
    container_name: "app"
    networks:
      intra:
        ipv4_address:  172.16.232.10
    ports:
    - 8081:8080
    links:
    - mongodb
    
networks:
  intra:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.232.0/24"