version: "3"

services:
  newman:
    image: postman/newman:ubuntu
    container_name: "newman"
    ports:
      - 27018:27018
    command: run "/tmp/collections/students.postman_collection.json" -e "/tmp/collections/local.postman_environment.json"
    volumes:
      - ./postman:/tmp/collections
    external_links:
      - 14315555/demo-restapi
    networks:
      intra:
        ipv4_address: 172.16.232.16

networks:
  intra:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.232.0/24"
